### ISSUE TITLE
Manufacturer Fields Not Showing Special Characters

### ISSUE THREAD

**Issue by cmenkemeller** [Justinlawrence102/rideTracker#28]
For Attraction Detail screen and Modify Details screen.

Examples-

Parks: Six Flags Over Texas

BATMAN The Ride (Bolliger & Mabillard) [Only shows as "Bolliger"]
JOKER, THE (S&S Worldwide) [Only shows as "S"]

**Comment by Justinlawrence102** [comment]
The problem is actually the ‘&’. It won’t work for the ride names too. When the URL reads the &, it thinks it’s at the end of the entry into the database
