### ISSUE TITLE
My Parks List- Last park blocked by plus

### ISSUE THREAD

**Issue by cmenkemeller** [Justinlawrence102/rideTracker#9]
Ride counts for the last park in My Parks list are blocked by +

**Comment by cmenkemeller** [comment]
Could you add a dummy cell at the bottom of the tableview? One additional cell would push the last park up over the button.

**Comment by cmenkemeller** [comment]
Or better yet-

https://stackoverflow.com/questions/27861685/ios-table-view-allow-scrolling-further-down-than-the-end

**Comment by Mark-Lawrence** [comment]
That second one looks promising. I'll look into it
